runtime: python312 

instance_class: F1

# entrypoint: gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind :$PORT app.main:application

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1

automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 0


